-- auto Generated on 2021-04-19
-- DROP TABLE IF EXISTS `plan`;
CREATE TABLE `plan`(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '姓名',
	age INT (11) NOT NULL DEFAULT -1 COMMENT '年龄',
	sex INT (11) NOT NULL DEFAULT -1 COMMENT '1男 0女',
	job VARCHAR (50) NOT NULL DEFAULT '' COMMENT '职业',
	address VARCHAR (50) NOT NULL DEFAULT '' COMMENT '家庭住址',
	phone VARCHAR (50) NOT NULL DEFAULT '' COMMENT '联系方式',
	disposal VARCHAR (50) NOT NULL DEFAULT '' COMMENT '处置情况',
	allergy VARCHAR (50) NOT NULL DEFAULT '' COMMENT '过敏史 1有 0无',
	cold VARCHAR (50) NOT NULL DEFAULT '' COMMENT '感冒 1有 0无',
	`degree` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '不适程度',
	opportunity VARCHAR (50) NOT NULL DEFAULT '' COMMENT '调理时机',
	`cycle` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '调理周期',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'plan';
